export enum ROUTE {
  HOME = "/",
  ARTICLES = "articles",
  ARTICLE_PAGE = "articles?_limit=12&_start=12",
  BLOGS = "blogs",
  SEARCH = "search",
  FAVORITES = "favorites",
  SING_IN = "sign-in",
  SIGN_UP = "sign-up",
  ARTICLE = "article/:id",
  BLOG = "blog/:id",
  NOT_FOUND = "*",
  ACCOUNT = "account",
  RESET = "reset",
}
